2023-05-24 15:27:18,481:DEBUG:certbot._internal.main:certbot version: 2.6.0
2023-05-24 15:27:18,481:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2023-05-24 15:27:18,481:DEBUG:certbot._internal.main:Arguments: ['-n', '-d', 'localhost.local', '--dns-route53', '--dry-run', '--agree-tos', '--email=admin@example.com']
2023-05-24 15:27:18,481:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#certbot-route53:auth,PluginEntryPoint#dns-route53,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2023-05-24 15:27:18,489:DEBUG:certbot._internal.log:Root logging level set at 30
2023-05-24 15:27:18,490:DEBUG:certbot._internal.plugins.selection:Requested authenticator dns-route53 and installer None
2023-05-24 15:27:18,493:DEBUG:botocore.hooks:Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2023-05-24 15:27:18,494:DEBUG:botocore.hooks:Changing event name from before-call.apigateway to before-call.api-gateway
2023-05-24 15:27:18,495:DEBUG:botocore.hooks:Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2023-05-24 15:27:18,496:DEBUG:botocore.hooks:Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2023-05-24 15:27:18,496:DEBUG:botocore.hooks:Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2023-05-24 15:27:18,496:DEBUG:botocore.hooks:Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2023-05-24 15:27:18,497:DEBUG:botocore.hooks:Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2023-05-24 15:27:18,498:DEBUG:botocore.hooks:Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2023-05-24 15:27:18,499:DEBUG:botocore.hooks:Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2023-05-24 15:27:18,499:DEBUG:botocore.hooks:Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2023-05-24 15:27:18,499:DEBUG:botocore.hooks:Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2023-05-24 15:27:18,501:DEBUG:botocore.utils:IMDS ENDPOINT: http://169.254.169.254/
2023-05-24 15:27:18,502:DEBUG:botocore.credentials:Looking for credentials via: env
2023-05-24 15:27:18,502:INFO:botocore.credentials:Found credentials in environment variables.
2023-05-24 15:27:18,503:DEBUG:botocore.loaders:Loading JSON file: /usr/local/lib/python3.10/site-packages/botocore/data/endpoints.json
2023-05-24 15:27:18,511:DEBUG:botocore.loaders:Loading JSON file: /usr/local/lib/python3.10/site-packages/botocore/data/sdk-default-configuration.json
2023-05-24 15:27:18,511:DEBUG:botocore.hooks:Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f99368f9000>
2023-05-24 15:27:18,527:DEBUG:botocore.loaders:Loading JSON file: /usr/local/lib/python3.10/site-packages/botocore/data/route53/2013-04-01/service-2.json
2023-05-24 15:27:18,540:DEBUG:botocore.loaders:Loading JSON file: /usr/local/lib/python3.10/site-packages/botocore/data/route53/2013-04-01/endpoint-rule-set-1.json.gz
2023-05-24 15:27:18,541:DEBUG:botocore.loaders:Loading JSON file: /usr/local/lib/python3.10/site-packages/botocore/data/partitions.json
2023-05-24 15:27:18,542:DEBUG:botocore.hooks:Event creating-client-class.route-53: calling handler <function add_generate_presigned_url at 0x7f9936890670>
2023-05-24 15:27:18,543:DEBUG:botocore.endpoint:Setting route53 timeout as (60, 60)
2023-05-24 15:27:18,544:DEBUG:botocore.loaders:Loading JSON file: /usr/local/lib/python3.10/site-packages/botocore/data/_retry.json
2023-05-24 15:27:18,545:DEBUG:botocore.client:Registering retry handlers for service: route53
2023-05-24 15:27:18,545:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * dns-route53
Description: Obtain certificates using a DNS TXT record (if you are using AWS Route53 for DNS).
Interfaces: Authenticator, Plugin
Entry point: dns-route53 = certbot_dns_route53._internal.dns_route53:Authenticator
Initialized: <certbot_dns_route53._internal.dns_route53.Authenticator object at 0x7f993679e710>
Prep: True
2023-05-24 15:27:18,545:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot_dns_route53._internal.dns_route53.Authenticator object at 0x7f993679e710> and installer None
2023-05-24 15:27:18,545:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator dns-route53, Installer None
2023-05-24 15:27:18,576:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-staging-v02.api.letsencrypt.org/acme/acct/103524564', new_authzr_uri=None, terms_of_service=None), 0421b70a6b4e0deb8728ba0f1c25dcb9, Meta(creation_dt=datetime.datetime(2023, 5, 24, 13, 24, 55, tzinfo=<UTC>), creation_host='e5c53c9fc7ed', register_to_eff=None))>
2023-05-24 15:27:18,577:DEBUG:acme.client:Sending GET request to https://acme-staging-v02.api.letsencrypt.org/directory.
2023-05-24 15:27:18,578:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-staging-v02.api.letsencrypt.org:443
2023-05-24 15:27:19,147:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 826
2023-05-24 15:27:19,148:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 24 May 2023 15:27:20 GMT
Content-Type: application/json
Content-Length: 826
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "-ZVtXHKPXfE": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-staging-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org/docs/staging-environment/"
  },
  "newAccount": "https://acme-staging-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-staging-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-staging-v02.api.letsencrypt.org/draft-ietf-acme-ari-01/renewalInfo/",
  "revokeCert": "https://acme-staging-v02.api.letsencrypt.org/acme/revoke-cert"
}
2023-05-24 15:27:19,148:DEBUG:certbot._internal.display.obj:Notifying user: Simulating a certificate request for localhost.local
2023-05-24 15:27:19,151:DEBUG:acme.client:Requesting fresh nonce
2023-05-24 15:27:19,152:DEBUG:acme.client:Sending HEAD request to https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce.
2023-05-24 15:27:19,343:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2023-05-24 15:27:19,343:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 24 May 2023 15:27:20 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: BEB9iQI9w-OBYf_AwGE5OAZ-hRJ3mU7hLWuMKjnB3flk5H0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2023-05-24 15:27:19,344:DEBUG:acme.client:Storing nonce: BEB9iQI9w-OBYf_AwGE5OAZ-hRJ3mU7hLWuMKjnB3flk5H0
2023-05-24 15:27:19,344:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "localhost.local"\n    }\n  ]\n}'
2023-05-24 15:27:19,345:DEBUG:acme.client:Sending POST request to https://acme-staging-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC8xMDM1MjQ1NjQiLCAibm9uY2UiOiAiQkVCOWlRSTl3LU9CWWZfQXdHRTVPQVotaFJKM21VN2hMV3VNS2puQjNmbGs1SDAiLCAidXJsIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvbmV3LW9yZGVyIn0",
  "signature": "pODiQIZr_bU44RNMKxbMXVbsHefp1QkDeJcowBBsjwawhr54UzVe0Va6LexLvqPbSRD1VqwaeXv15xcWV2-onyEh9V9fnMjjjE4tkL6Cvb9d5YbB5-oibVw6jGs-NejNDvMnuqyQ_QAQjnIgYz2atY3J4D5Uu-Cz-zr99r4wZ57zhEqmTWcQKVZtC7UfyQ7xkaOjGdcmIWaUYY9I-lf8yjnvDbfjW7aTgNSU7-rzGo8gLimNWN5Iz-bUroSxC5iv1SHzmY6plAJ_-fY4uY7y_wAPVn3DFvOTtZIvHBTmkaOGkVWKY0jOZeo15cwW7l9KJXdQvc8-AQ33igG9B7esaw",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImxvY2FsaG9zdC5sb2NhbCIKICAgIH0KICBdCn0"
}
2023-05-24 15:27:19,540:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 400 217
2023-05-24 15:27:19,540:DEBUG:acme.client:Received response:
HTTP 400
Server: nginx
Date: Wed, 24 May 2023 15:27:20 GMT
Content-Type: application/problem+json
Content-Length: 217
Connection: keep-alive
Boulder-Requester: 103524564
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: BEB9Qgx-ibOStEXpWLVM83xd83hDQbKfwB28ry3ek8xayx0

{
  "type": "urn:ietf:params:acme:error:rejectedIdentifier",
  "detail": "Error creating new order :: Cannot issue for \"localhost.local\": Domain name does not end with a valid public suffix (TLD)",
  "status": 400
}
2023-05-24 15:27:19,541:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1864, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1597, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 141, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 478, in _get_order_and_authorizations
    orderr = self.acme.new_order(csr_pem)
  File "/opt/certbot/src/acme/acme/client.py", line 138, in new_order
    response = self._post(self.directory['newOrder'], order)
  File "/opt/certbot/src/acme/acme/client.py", line 366, in _post
    return self.net.post(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 739, in post
    return self._post_once(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 752, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/opt/certbot/src/acme/acme/client.py", line 603, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:rejectedIdentifier :: The server will not issue certificates for the identifier :: Error creating new order :: Cannot issue for "localhost.local": Domain name does not end with a valid public suffix (TLD)
2023-05-24 15:27:19,541:ERROR:certbot._internal.log:An unexpected error occurred:
2023-05-24 15:27:19,541:ERROR:certbot._internal.log:Error creating new order :: Cannot issue for "localhost.local": Domain name does not end with a valid public suffix (TLD)
